# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# 
name: test

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "services/fjord/**/*"
      - ".github/workflows/test.yml"

jobs:
  github-actions-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: earthly/actions-setup@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Authenticate to Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: build
        run: |
          sudo -E env PATH=$PATH earthly --ci +docker
     
  self-hosted:
    runs-on: self-hosted
    timeout-minutes: 1
    steps:
      - uses: earthly/actions-setup@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Authenticate to Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: build
        run: |
          sudo -E env PATH=$PATH earthly --ci +docker

